-
    given: "Arghya"
    family: "Dutta"
    orcid: "0000-0003-2116-6475"
-
    given: "Dirk"
    family: "Schneider"
    orcid: "0000-0003-4517-6387"
-
    given: "Andrew L."
    family: "Ferguson"
    orcid: "0000-0002-8829-9726"
-
    given: "Akshaya K."
    family: "Das"
    orcid: "0000-0002-5577-3161"
-
    given: "Luca M."
    family: "Ghiringhelli"
    orcid: "0000-0001-5099-3029"
-
    given: "Michael"
    family: "Vogel"
    orcid: "0000-0003-2706-3522"
-
    given: "Tanja"
    family: "Weil"
    orcid: "0000-0002-5906-7205"
-
    given: "Martin"
    family: "Girard"
    orcid: "0000-0003-2051-6218"
-
    given: "Yasemin"
    family: "Bozkurt Varolgüneş"
    orcid: "0000-0002-9179-2458"
-
    given: "Christoph"
    family: "Scherer"
    orcid: "0000-0003-2587-4567"

