-
    given: "Tristan"
    family: "Bereau"
    orcid: "0000-0001-9945-1271"
    twitter: "https://twitter.com/tristanbereau"
    github: "https://github.com/tbereau"
    scholar: "https://scholar.google.com/citations?user=9cYdrBUAAAAJ"
    image: "tristan.jpg"
    categories:
        - current
        - group leader
    summary: "Tristan Bereau heads the group. Besides from science and data, Tristan enjoys spending time outside and playing jazz piano."
    experience:
        - "Professor @ Uni. Heidelberg | 2023 -"
        - "Quant @ IMC Trading | 2022"
        - "Assistant Professor @ Uni. Amsterdam | 2020 - 2021"
        - "Emmy Noether group leader @ Max Planck Institute for Polymer Research | 2014 - 2019"
        - "Postdoc @ Uni. Basel | 2012 - 2013"
    education:
        - "PhD, Physics, Carnegie Mellon University | 2006 - 2011"
        - "BSc, Physics, Ecole Polytechnique Fédérale de Lausanne | 2003 - 2006"
-
    given: "Arghya"
    family: "Dutta"
    orcid: "0000-0003-2116-6475"
    image: "dutta.jpg"
    website: "https://arghyadutta.github.io"
    categories:
        - alumnus
        - postdoc
-
    given: "Dirk"
    family: "Schneider"
    orcid: "0000-0003-4517-6387"
-
    given: "Andrew L."
    family: "Ferguson"
    orcid: "0000-0002-8829-9726"
-
    given: "Akshaya K."
    family: "Das"
    orcid: "0000-0002-5577-3161"
-
    given: "Luca M."
    family: "Ghiringhelli"
    orcid: "0000-0001-5099-3029"
-
    given: "Michael"
    family: "Vogel"
    orcid: "0000-0003-2706-3522"
-
    given: "Tanja"
    family: "Weil"
    orcid: "0000-0002-5906-7205"
-
    given: "Martin"
    family: "Girard"
    orcid: "0000-0003-2051-6218"
    categories:
        - alumnus
        - postdoc
-
    given: "Yasemin"
    family: "Bozkurt Varolgüneş"
    orcid: "0000-0002-9179-2458"
    categories:
        - alumnus
        - exchange phd student
    image:
        "bozkurt.jpg"
-
    given: "Christoph"
    family: "Scherer"
    orcid: "0000-0003-2587-4567"
-
    given: "Bernadette"
    family: "Mohr"
    categories:
        - alumnus
        - phd student
    image: "mohr.jpg"
-
    given: "Atreyee"
    family: "Banerjee"
    categories:
        - alumnus
        - postdoc
-
    given: "Marius"
    family: "Bause"
    categories:
        - alumnus
        - postdoc
    image: "bause.jpg"
-
    given: "Alessia"
    family: "Centi"
    categories:
        - alumnus
        - postdoc
    image: "centi.jpg"
-
    given: "Christian"
    family: "Hoffmann"
    categories:
        - alumnus
        - diplom student
-
    given: "Kiran"
    family: "Kanekal"
    categories:
        - alumnus
        - phd student
    image: "kanekal.jpg"
-
    given: "Chan"
    family: "Liu"
    categories:
        - alumnus
        - phd student
-
    given: "Roberto"
    family: "Menichetti"
    categories:
        - alumnus
        - postdoc
-
    given: "Clemens"
    family: "Rauer"
    categories:
        - alumnus
        - postdoc
    image: "rauer.jpg"
-
    given: "Joseph"
    family: "Rudzinski"
    categories:
        - alumnus
        - postdoc
    image: "rudzinski.jpg"
-
    given: "René"
    family: "Scheid"
    categories:
        - alumnus
        - master student
-
    given: "Marc"
    family: "Stieffenhofer"
    categories:
        - alumnus
        - phd student
    image: "stieffenhofer.jpeg"
-
    given: "Timon"
    family: "Wittenstein"
    categories:
        - alumnus
        - master student
-
    given: "Svenja"
    family: "Wörner"
    categories:
        - alumnus
        - phd student
    image: "woerner.jpg"

