project:
    type: website
    output-dir: _site
    resources:
        - "files/*"

website:
    twitter-card: true
    site-url: https://tristanbereau.com
    title: "Tristan Bereau"
    search:
        type: overlay
        location: navbar
    navbar:
        background: light
        left:
            -   href: index.qmd
                text: Home
            -   text: Research
                menu:
                    -   text: Landscape
                        icon: geo-alt
                        href: research_landscape.qmd
                    -   text: Topics
                        icon: lightbulb
                        href: research_topics.qmd
                    -   text: Publications
                        icon: file-earmark-text
                        href: papers.qmd
                    -   text: Notes
                        icon: journal-text
                        href: notes.qmd
            -   text: Group
                menu:
                    -   text: Members
                        icon: file-person
                        href: group_members.qmd
                    -   text: Positions
                        icon: person-plus
                        href: positions.qmd
            - about.qmd
            - contact.qmd
        right:
            -   icon: twitter
                href: https://twitter.com/tristanbereau
            -   icon: google
                href: https://scholar.google.com/citations?user=9cYdrBUAAAAJ
            -   icon: file-earmark-person
                href: /files/bereau_cv.pdf
    page-footer:
        right: |
            Tristan Bereau, [Institute for Theoretical Physics](https://www.thphys.uni-heidelberg.de),
            [Heidelberg University](https://www.uni-heidelberg.de/en)

format:
    html:
        toc: true
        theme:
            light:
                - cosmo
                - theme.scss
        code-copy: true
        code-overflow: wrap
        css: styles.css
        grid:
            sidebar-width: 250px
            body-width: 900px
            margin-width: 300px
        include-in-header:
            -   file: header_goatcounter.html

execute:
    freeze: auto
