project:
  type: website
  output-dir: _site

website:
  title: "Bereau group"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - research_landscape.qmd
      - papers.qmd
      - team.qmd
      - about.qmd
      - contact.qmd

format:
  html:
    toc: true
    theme:
      light:
        - cosmo
        - theme.scss
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


